library:
  join: json-serialize.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle.js:
          json-serialize: json-serialize.js
      no_files_ok: ['test/core', 'test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'